[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
once_cell = "1.21.3"
rstar = "0.12.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3
panic = "abort"
codegen-units = 1
lto = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"

[profile.dev.package."*"]
opt-level = 2
