[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
log = "0.4.27"
rstar = "0.12.2"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
panic = "abort"
codegen-units = 1
lto = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"

[profile.dev.package."*"]
opt-level = 2
